<a href="https://colab.research.google.com/github/shalini1291/pyspark_practise/blob/main/practise_pyspark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=5fc370e584946a08c8f2f561997820b9177deb8f61d5ebb73dc47a01bbb1f7ac
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession \
.builder \
.appName("Python Spark create RDD example") \
.config("spark.some.config.option", "some-value") \
.getOrCreate()
df = spark.sparkContext\
.parallelize([(1, 2, 3, 'a b c'),
(4, 5, 6, 'd e f'),
(7, 8, 9, 'g h i')])\
.toDF(['col1', 'col2', 'col3','col4'])
df.show()

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.sparkContext.parallelize([(1,2,'ab'),(2,4,'ef'),(3,6,'lm')]).toDF(['col1','col2','col3'])
df.show()

+----+----+----+
|col1|col2|col3|
+----+----+----+
|   1|   2|  ab|
|   2|   4|  ef|
|   3|   6|  lm|
+----+----+----+

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.sparkContext.parallelize([(1,2,'ab'),(2,4,'ef'),(3,6,'lm')])
df.collect()

[(1, 2, 'ab'), (2, 4, 'ef'), (3, 6, 'lm')]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
emp=spark.createDataFrame([(1,2,'ab'),(2,4,'ef'),(3,6,'lm')])
emp.collect()

[Row(_1=1, _2=2, _3='ab'), Row(_1=2, _2=4, _3='ef'), Row(_1=3, _2=6, _3='lm')]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
d1=spark.read.format('csv').option('header','true').load('/content/sample_data/mnist_train_small.csv')
d1.show(5)

+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+------+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+------+---+------+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+---+------+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+---+----+----+----+----+----+----+----+----+---+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+---+---+------+------+----+----+----+----+----+----+----+---+---+------+------+------+---+---+----+----+----+----+----+----+----+----+----+---+---+------+---+---+----+----+----+----+----+-----+------+------+------+------+------+------+------+------+----+----+----+----+----+----+----+----+----+------+------+------+---+----+----+----+----+----+-----+------+------+------+---+---+---+------+------+---+----+----+----+----+----+----+----+----+-----+------+------+------+-----+----+----+----+----+---+------+------+------+-----+---+----+----+---+------+------+----+----+----+----+----+----+----+----+-----+------+------+---+----+----+----+----+-----+------+---+------+---+----+----+----+----+---+------+---+----+----+----+----+----+----+----+----+------+------+------+---+----+----+----+-----+------+------+---+---+---+----+----+----+----+---+------+-----+----+----+----+----+----+----+----+----+------+------+---+----+----+----+----+------+------+------+---+----+----+----+----+----+-----+------+---+----+----+----+----+----+----+----+----+----+------+------+-----+----+----+----+---+------+---+-----+----+----+----+----+----+---+---+---+----+----+----+----+----+----+----+----+----+----+------+------+---+----+----+----+---+------+---+----+----+----+-----+---+---+------+---+-----+----+----+----+----+----+----+----+----+----+----+------+------+---+----+----+---+------+------+-----+---+-----+---+------+------+------+------+----+----+----+----+----+----+----+----+----+----+----+----+------+------+---+------+---+------+------+------+---+---+------+------+------+---+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+------+------+------+------+------+------+------+------+---+---+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|  6| 01| 02| 03| 04| 05| 06| 07| 08| 09|010|011|012|013|014|015|016|017|018|019|020|021|022|023|024|025|026|027|028|029|030|031|032|033|034|035|036|037|038|039|040|041|042|043|044|045|046|047|048|049|050|051|052|053|054|055|056|057|058|059|060|061|062|063|064|065|066|067|068|069|070|071|072|073|074|075|076|077|078|079|080|081|082|083|084|085|086|087|088|089|090|091|092|093|094|095|096|097|098|099|0100|0101|0102|0103|0104|0105|0106|0107|0108|0109|0110|0111|0112|0113|0114|0115|0116|0117|0118|0119|0120|0121|0122|24123|67124|67125| 18|0127|0128|0129|0130|0131|0132|0133|0134|0135|0136|0137|0138|0139|0140|0141|0142|0143|0144|0145|0146|0147|0148|0149|0150|131|252152|252153|66154|0155|0156|0157|0158|0159|0160|0161|0162|0163|0164|0165|0166|0167|0168|0169|0170|0171|0172|0173|0174|0175|0176|0177|159178|250|232180| 30| 32|0183|0184|0185|0186|0187|0188|0189|0190|0191|0192|0193|0194|0195|0196|0197|0198|0199|0200|0201|0202|0203|0204|15205|222|252207|108|0209|0210|0211|0212|0213|0214|0215|0216|0217|0218|0219|0220|0221|0222|0223|0224|0225|0226|0227|0228|0229|0230|0231|0232|147|252234|183|5236|0237|0238|0239|0240|0241|0242|0243| 20|89245|89246| 73|0248|0249|0250|0251|0252|0253|0254|0255|0256|0257|0258|0259| 48|247|252262|159263|0264|0265|0266|0267|0268|0269|0270| 79|236|252273|252274|249275|198| 16|0278|0279|0280|0281|0282|0283|0284|0285|0286| 41|193|252289|199| 22|0292|0293|0294|0295|0296|12297|135298|248299|252300|252301|252302|252303|252304|100305|0306|0307|0308|0309|0310|0311|0312|0313|0314|100315|252316|252317| 88|0319|0320|0321|0322|0323|11324|171325|252326|252327|235|175|178|252331|252332|224|0334|0335|0336|0337|0338|0339|0340|0341|15342|209343|252344|233345|12346|0347|0348|0349|0350| 49|177352|252353|252354|89355| 26|0357|2358|166|252360|252361|0362|0363|0364|0365|0366|0367|0368|0369|96370|253371|253372| 59|0374|0375|0376|0377|11378|177379|255|253381| 92|0383|0384|0385|0386|155|253388|128|0390|0391|0392|0393|0394|0395|0396|0397|143398|252399|252400| 10|0402|0403|0404|12405|171406|252407|216|110| 13|0411|0412|0413|3414|180|232416|24417|0418|0419|0420|0421|0422|0423|0424|0425|143426|252427|170|2429|0430|0431|0432|135433|252434|209435| 19|0437|0438|0439|0440|0441|12442|252443|132|0445|0446|0447|0448|0449|0450|0451|0452|0453|249454|252455|96456|0457|0458|0459| 21|248461|246|34463|0464|0465|0466|0467|5468| 61|234|152|3472|0473|0474|0475|0476|0477|0478|0479|0480|0481|253482|252483| 44|0485|0486|0487|145|252489|104|0491|0492|0493|46494|114|184|252497|149|34499|0500|0501|0502|0503|0504|0505|0506|0507|0508|0509|253510|252511| 82|0513|0514| 31|239516|252517|66518| 39|89520|165|243522|252523|233524|126525|5526|0527|0528|0529|0530|0531|0532|0533|0534|0535|0536|0537|249538|252539|244|126541| 98|143543|252544|252545|237|240|253548|252549|243550|174|17552|0553|0554|0555|0556|0557|0558|0559|0560|0561|0562|0563|0564|0565|119|239567|252568|252569|252570|252571|252572|252573|252574|252575|228|179|17578|0579|0580|0581|0582|0583|0584|0585|0586|0587|0588|0589|0590|0591|0592|0593|0594|46595|66596|66597|66598|66599|66600|66601|66602|66603| 29|0605|0606|0607|0608|0609|0610|0611|0612|0613|0614|0615|0616|0617|0618|0619|0620|0621|0622|0623|0624|0625|0626|0627|0628|0629|0630|0631|0632|0633|0634|0635|0636|0637|0638|0639|0640|0641|0642|0643|0644|0645|0646|0647|0648|0649|0650|0651|0652|0653|0654|0655|0656|0657|0658|0659|0660|0661|0662|0663|0664|0665|0666|0667|0668|0669|0670|0671|0672|0673|0674|0675|0676|0677|0678|0679|0680|0681|0682|0683|0684|0685|0686|0687|0688|0689|0690|0691|0692|0693|0694|0695|0696|0697|0698|0699|0700|0701|0702|0703|0704|0705|0706|0707|0708|0709|0710|0711|0712|0713|0714|0715|0716|0717|0718|0719|0720|0721|0722|0723|0724|0725|0726|0727|0728|0729|0730|0731|0732|0733|0734|0735|0736|0737|0738|0739|0740|0741|0742|0743|0744|0745|0746|0747|0748|0749|0750|0751|0752|0753|0754|0755|0756|0757|0758|0759|0760|0761|0762|0763|0764|0765|0766|0767|0768|0769|0770|0771|0772|0773|0774|0775|0776|0777|0778|0779|0780|0781|0782|0783|0784|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+------+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+------+---+------+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+---+------+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+---+----+----+----+----+----+----+----+----+---+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+---+---+------+------+----+----+----+----+----+----+----+---+---+------+------+------+---+---+----+----+----+----+----+----+----+----+----+---+---+------+---+---+----+----+----+----+----+-----+------+------+------+------+------+------+------+------+----+----+----+----+----+----+----+----+----+------+------+------+---+----+----+----+----+----+-----+------+------+------+---+---+---+------+------+---+----+----+----+----+----+----+----+----+-----+------+------+------+-----+----+----+----+----+---+------+------+------+-----+---+----+----+---+------+------+----+----+----+----+----+----+----+----+-----+------+------+---+----+----+----+----+-----+------+---+------+---+----+----+----+----+---+------+---+----+----+----+----+----+----+----+----+------+------+------+---+----+----+----+-----+------+------+---+---+---+----+----+----+----+---+------+-----+----+----+----+----+----+----+----+----+------+------+---+----+----+----+----+------+------+------+---+----+----+----+----+----+-----+------+---+----+----+----+----+----+----+----+----+----+------+------+-----+----+----+----+---+------+---+-----+----+----+----+----+----+---+---+---+----+----+----+----+----+----+----+----+----+----+------+------+---+----+----+----+---+------+---+----+----+----+-----+---+---+------+---+-----+----+----+----+----+----+----+----+----+----+----+------+------+---+----+----+---+------+------+-----+---+-----+---+------+------+------+------+----+----+----+----+----+----+----+----+----+----+----+----+------+------+---+------+---+------+------+------+---+---+------+------+------+---+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+---+------+------+------+------+------+------+------+------+------+---+---+-----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|  5|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|    0|    0|    0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|    28|    59|   50|   0|  23|   0|   0|  32| 134| 180| 254| 206|   8|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   4|    96|216|   233|254|248| 215| 231| 215| 215| 236| 254| 250| 181|  27|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  108|254|   254|247| 175| 175| 175| 176| 175| 175| 205| 175|  60|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0| 47|   254|245|  85|   0|   0|   0|   0|   0|   0|   8|  0|    0|    0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|152|   254|   158|   0|   0|   0|   0|   0|   0|   0|  0|  0|     0|     0|     0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0| 19|   240|255| 38|   0|  41|  50|   0|   0|    0|     0|     0|     0|     0|     0|     0|     0|     0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|    87|   254|254| 178| 215| 242| 248| 215|   96|    19|     0|     0|  0|  0|  0|     0|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|    0|     0|   176|   254|  254| 254| 217| 175| 187|254|   254|   248|    85|    0|  0|   0|   0|  0|     0|     0|   0|   0|   0|   0|   0|   0|   0|   0|    0|     0|   161|247| 214|  57|  11|   0|    3|    19|177|   248|248| 129|   9|   0|   0|  0|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|    18| 49|   0|   0|   0|    0|     0|     0|  0| 57|224| 254| 171|   0|   0|  0|     0|    0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|  0|   0|   0|   0|   0|     0|     0|     0|  0|   0|   0| 213| 255| 122|    0|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|    0|   0|   0|   0|  0|     0|  0|    0|   0|   0|   0|  92| 254|196|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|  0|   0|   0|   0|  0|     0|  0|   0|   0|   0|    0| 40|254|   196|  0|    0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|  0|   0|   0|  0|     0|     0|    0|  0|    0|  0|     0|   145|   254|   196|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0| 31|   188| 45|     0|     0|     0|  0|  0|     0|     0|    99|249|  254| 121|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|     0|   139|   245|    45|     0|     0|     0|     0|     0|  0|140|  254| 254| 133|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   17|  242|  169|    0|    0|    0|    0|    4|   58|216| 248| 254| 167|   9|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  14| 230| 196|  79|  49|  79|  79| 181| 254| 254| 247| 108|   6|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  44| 213| 254| 247| 254| 254| 254| 254| 192|  32|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   9| 133| 156| 193| 155| 140|  58|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  7|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|    0|    0|    0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|     0|     0|    0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|  0|     0|  0|  0|   0|   0|   0|  32|  97| 179| 254| 223|  72|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|    0|  0|     0|  0|   0|   0|  13|  65| 185| 235| 253| 254| 253| 253| 199|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|     0| 37|  55|   0|  61| 224| 253| 253| 253| 192| 78|  226|  253|213|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|  0|   100|   228| 247| 159| 248| 254| 234| 183|  64|  5|  0|   177|   253|   161|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|  0|    76|254|253| 253| 253| 253| 193|  46|    0|     0|     0|     0|   214|   253|   117|     0|     0|   0|   0|   0|   0|   0|   0|   0|   0|   0|     0|     0|   121|255| 254| 254| 146|  60|   0|    0|     0|     0|     0| 14|224|254|    57|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|    0|     0|    79|   244|  254| 243| 106|   3|   0|  0|     0|     0|     0|    0|186| 253| 216| 10|     0|     0|   0|   0|   0|   0|   0|   0|   0|   0|    0|     0|   166|253| 254| 135|   0|   0|    0|     0|  0|     0|  0|   0| 254| 253| 107|  0|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|     0|   126|   251|253| 146|   3|   0|    0|     0|     0|  0|  0|  0| 106| 254| 242|  36|  0|     0|    0|   0|   0|   0|   0|   0|   0|   0|   0|     8|   205|253| 215|  23|   0|   0|     0|     0|     0|  0|   0|  31| 239| 254| 121|    0|     0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   178|   254|  244|  83|   0|   0|  0|     0|  0|    0|   0|  19| 201| 254| 196| 15|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  28|   232|   253|124|   0|   0|   0|  0|     0|  0|   0|   2| 129|  253|253| 15|     0|  0|    0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  18|   220|   174| 13|   0|   0|  0|     0|     0|    0|  0|   88|253|   253|   154|     0|     0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|    15|     0|  0|     0|  0|     0|     0|     0|  0| 10|   175|   253|   231| 27|    0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  0|     0|     0|     0|     0|     0|     0|     0|     0|   134|253|253|  138|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|    0|    0|    0|    0|    0|    0|    0|   83|  255|254| 152|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|  19| 222| 254| 191|  12|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0| 137| 253| 254| 135|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0| 234| 253| 254| 173|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0| 159| 253| 193|  46|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|

In [ ]:
d1.printSchema()

root
 |-- 6: string (nullable = true)
 |-- 01: string (nullable = true)
 |-- 02: string (nullable = true)
 |-- 03: string (nullable = true)
 |-- 04: string (nullable = true)
 |-- 05: string (nullable = true)
 |-- 06: string (nullable = true)
 |-- 07: string (nullable = true)
 |-- 08: string (nullable = true)
 |-- 09: string (nullable = true)
 |-- 010: string (nullable = true)
 |-- 011: string (nullable = true)
 |-- 012: string (nullable = true)
 |-- 013: string (nullable = true)
 |-- 014: string (nullable = true)
 |-- 015: string (nullable = true)
 |-- 016: string (nullable = true)
 |-- 017: string (nullable = true)
 |-- 018: string (nullable = true)
 |-- 019: string (nullable = true)
 |-- 020: string (nullable = true)
 |-- 021: string (nullable = true)
 |-- 022: string (nullable = true)
 |-- 023: string (nullable = true)
 |-- 024: string (nullable = true)
 |-- 025: string (nullable = true)
 |-- 026: string (nullable = true)
 |-- 027: string (nullable = true)
 |-- 028: string (nullable = true)
 |-- 029: string (nullable = true)
 |-- 030: string (nullable = true)
 |-- 031: string (nullable = true)
 |-- 032: string (nullable = true)
 |-- 033: string (nullable = true)
 |-- 034: string (nullable = true)
 |-- 035: string (nullable = true)
 |-- 036: string (nullable = true)
 |-- 037: string (nullable = true)
 |-- 038: string (nullable = true)
 |-- 039: string (nullable = true)
 |-- 040: string (nullable = true)
 |-- 041: string (nullable = true)
 |-- 042: string (nullable = true)
 |-- 043: string (nullable = true)
 |-- 044: string (nullable = true)
 |-- 045: string (nullable = true)
 |-- 046: string (nullable = true)
 |-- 047: string (nullable = true)
 |-- 048: string (nullable = true)
 |-- 049: string (nullable = true)
 |-- 050: string (nullable = true)
 |-- 051: string (nullable = true)
 |-- 052: string (nullable = true)
 |-- 053: string (nullable = true)
 |-- 054: string (nullable = true)
 |-- 055: string (nullable = true)
 |-- 056: string (nullable = true)
 |-- 057: string (nullable = true)
 |-- 058: string (nullable = true)
 |-- 059: string (nullable = true)
 |-- 060: string (nullable = true)
 |-- 061: string (nullable = true)
 |-- 062: string (nullable = true)
 |-- 063: string (nullable = true)
 |-- 064: string (nullable = true)
 |-- 065: string (nullable = true)
 |-- 066: string (nullable = true)
 |-- 067: string (nullable = true)
 |-- 068: string (nullable = true)
 |-- 069: string (nullable = true)
 |-- 070: string (nullable = true)
 |-- 071: string (nullable = true)
 |-- 072: string (nullable = true)
 |-- 073: string (nullable = true)
 |-- 074: string (nullable = true)
 |-- 075: string (nullable = true)
 |-- 076: string (nullable = true)
 |-- 077: string (nullable = true)
 |-- 078: string (nullable = true)
 |-- 079: string (nullable = true)
 |-- 080: string (nullable = true)
 |-- 081: string (nullable = true)
 |-- 082: string (nullable = true)
 |-- 083: string (nullable = true)
 |-- 084: string (nullable = true)
 |-- 085: string (nullable = true)
 |-- 086: string (nullable = true)
 |-- 087: string (nullable = true)
 |-- 088: string (nullable = true)
 |-- 089: string (nullable = true)
 |-- 090: string (nullable = true)
 |-- 091: string (nullable = true)
 |-- 092: string (nullable = true)
 |-- 093: string (nullable = true)
 |-- 094: string (nullable = true)
 |-- 095: string (nullable = true)
 |-- 096: string (nullable = true)
 |-- 097: string (nullable = true)
 |-- 098: string (nullable = true)
 |-- 099: string (nullable = true)
 |-- 0100: string (nullable = true)
 |-- 0101: string (nullable = true)
 |-- 0102: string (nullable = true)
 |-- 0103: string (nullable = true)
 |-- 0104: string (nullable = true)
 |-- 0105: string (nullable = true)
 |-- 0106: string (nullable = true)
 |-- 0107: string (nullable = true)
 |-- 0108: string (nullable = true)
 |-- 0109: string (nullable = true)
 |-- 0110: string (nullable = true)
 |-- 0111: string (nullable = true)
 |-- 0112: string (nullable = true)
 |-- 0113: string (nullable = true)
 |-- 0114: string (nullable = true)
 |-- 0115: string (nullable = true)
 |-- 0116: string (nullable = true)
 |-- 0117: string (nullable = true)
 |-- 0118: string (nullable = true)
 |-- 0119: string (nullable = true)
 |-- 0120: string (nullable = true)
 |-- 0121: string (nullable = true)
 |-- 0122: string (nullable = true)
 |-- 24123: string (nullable = true)
 |-- 67124: string (nullable = true)
 |-- 67125: string (nullable = true)
 |-- 18: string (nullable = true)
 |-- 0127: string (nullable = true)
 |-- 0128: string (nullable = true)
 |-- 0129: string (nullable = true)
 |-- 0130: string (nullable = true)
 |-- 0131: string (nullable = true)
 |-- 0132: string (nullable = true)
 |-- 0133: string (nullable = true)
 |-- 0134: string (nullable = true)
 |-- 0135: string (nullable = true)
 |-- 0136: string (nullable = true)
 |-- 0137: string (nullable = true)
 |-- 0138: string (nullable = true)
 |-- 0139: string (nullable = true)
 |-- 0140: string (nullable = true)
 |-- 0141: string (nullable = true)
 |-- 0142: string (nullable = true)
 |-- 0143: string (nullable = true)
 |-- 0144: string (nullable = true)
 |-- 0145: string (nullable = true)
 |-- 0146: string (nullable = true)
 |-- 0147: string (nullable = true)
 |-- 0148: string (nullable = true)
 |-- 0149: string (nullable = true)
 |-- 0150: string (nullable = true)
 |-- 131: string (nullable = true)
 |-- 252152: string (nullable = true)
 |-- 252153: string (nullable = true)
 |-- 66154: string (nullable = true)
 |-- 0155: string (nullable = true)
 |-- 0156: string (nullable = true)
 |-- 0157: string (nullable = true)
 |-- 0158: string (nullable = true)
 |-- 0159: string (nullable = true)
 |-- 0160: string (nullable = true)
 |-- 0161: string (nullable = true)
 |-- 0162: string (nullable = true)
 |-- 0163: string (nullable = true)
 |-- 0164: string (nullable = true)
 |-- 0165: string (nullable = true)
 |-- 0166: string (nullable = true)
 |-- 0167: string (nullable = true)
 |-- 0168: string (nullable = true)
 |-- 0169: string (nullable = true)
 |-- 0170: string (nullable = true)
 |-- 0171: string (nullable = true)
 |-- 0172: string (nullable = true)
 |-- 0173: string (nullable = true)
 |-- 0174: string (nullable = true)
 |-- 0175: string (nullable = true)
 |-- 0176: string (nullable = true)
 |-- 0177: string (nullable = true)
 |-- 159178: string (nullable = true)
 |-- 250: string (nullable = true)
 |-- 232180: string (nullable = true)
 |-- 30: string (nullable = true)
 |-- 32: string (nullable = true)
 |-- 0183: string (nullable = true)
 |-- 0184: string (nullable = true)
 |-- 0185: string (nullable = true)
 |-- 0186: string (nullable = true)
 |-- 0187: string (nullable = true)
 |-- 0188: string (nullable = true)
 |-- 0189: string (nullable = true)
 |-- 0190: string (nullable = true)
 |-- 0191: string (nullable = true)
 |-- 0192: string (nullable = true)
 |-- 0193: string (nullable = true)
 |-- 0194: string (nullable = true)
 |-- 0195: string (nullable = true)
 |-- 0196: string (nullable = true)
 |-- 0197: string (nullable = true)
 |-- 0198: string (nullable = true)
 |-- 0199: string (nullable = true)
 |-- 0200: string (nullable = true)
 |-- 0201: string (nullable = true)
 |-- 0202: string (nullable = true)
 |-- 0203: string (nullable = true)
 |-- 0204: string (nullable = true)
 |-- 15205: string (nullable = true)
 |-- 222: string (nullable = true)
 |-- 252207: string (nullable = true)
 |-- 108: string (nullable = true)
 |-- 0209: string (nullable = true)
 |-- 0210: string (nullable = true)
 |-- 0211: string (nullable = true)
 |-- 0212: string (nullable = true)
 |-- 0213: string (nullable = true)
 |-- 0214: string (nullable = true)
 |-- 0215: string (nullable = true)
 |-- 0216: string (nullable = true)
 |-- 0217: string (nullable = true)
 |-- 0218: string (nullable = true)
 |-- 0219: string (nullable = true)
 |-- 0220: string (nullable = true)
 |-- 0221: string (nullable = true)
 |-- 0222: string (nullable = true)
 |-- 0223: string (nullable = true)
 |-- 0224: string (nullable = true)
 |-- 0225: string (nullable = true)
 |-- 0226: string (nullable = true)
 |-- 0227: string (nullable = true)
 |-- 0228: string (nullable = true)
 |-- 0229: string (nullable = true)
 |-- 0230: string (nullable = true)
 |-- 0231: string (nullable = true)
 |-- 0232: string (nullable = true)
 |-- 147: string (nullable = true)
 |-- 252234: string (nullable = true)
 |-- 183: string (nullable = true)
 |-- 5236: string (nullable = true)
 |-- 0237: string (nullable = true)
 |-- 0238: string (nullable = true)
 |-- 0239: string (nullable = true)
 |-- 0240: string (nullable = true)
 |-- 0241: string (nullable = true)
 |-- 0242: string (nullable = true)
 |-- 0243: string (nullable = true)
 |-- 20: string (nullable = true)
 |-- 89245: string (nullable = true)
 |-- 89246: string (nullable = true)
 |-- 73: string (nullable = true)
 |-- 0248: string (nullable = true)
 |-- 0249: string (nullable = true)
 |-- 0250: string (nullable = true)
 |-- 0251: string (nullable = true)
 |-- 0252: string (nullable = true)
 |-- 0253: string (nullable = true)
 |-- 0254: string (nullable = true)
 |-- 0255: string (nullable = true)
 |-- 0256: string (nullable = true)
 |-- 0257: string (nullable = true)
 |-- 0258: string (nullable = true)
 |-- 0259: string (nullable = true)
 |-- 48: string (nullable = true)
 |-- 247: string (nullable = true)
 |-- 252262: string (nullable = true)
 |-- 159263: string (nullable = true)
 |-- 0264: string (nullable = true)
 |-- 0265: string (nullable = true)
 |-- 0266: string (nullable = true)
 |-- 0267: string (nullable = true)
 |-- 0268: string (nullable = true)
 |-- 0269: string (nullable = true)
 |-- 0270: string (nullable = true)
 |-- 79: string (nullable = true)
 |-- 236: string (nullable = true)
 |-- 252273: string (nullable = true)
 |-- 252274: string (nullable = true)
 |-- 249275: string (nullable = true)
 |-- 198: string (nullable = true)
 |-- 16: string (nullable = true)
 |-- 0278: string (nullable = true)
 |-- 0279: string (nullable = true)
 |-- 0280: string (nullable = true)
 |-- 0281: string (nullable = true)
 |-- 0282: string (nullable = true)
 |-- 0283: string (nullable = true)
 |-- 0284: string (nullable = true)
 |-- 0285: string (nullable = true)
 |-- 0286: string (nullable = true)
 |-- 41: string (nullable = true)
 |-- 193: string (nullable = true)
 |-- 252289: string (nullable = true)
 |-- 199: string (nullable = true)
 |-- 22: string (nullable = true)
 |-- 0292: string (nullable = true)
 |-- 0293: string (nullable = true)
 |-- 0294: string (nullable = true)
 |-- 0295: string (nullable = true)
 |-- 0296: string (nullable = true)
 |-- 12297: string (nullable = true)
 |-- 135298: string (nullable = true)
 |-- 248299: string (nullable = true)
 |-- 252300: string (nullable = true)
 |-- 252301: string (nullable = true)
 |-- 252302: string (nullable = true)
 |-- 252303: string (nullable = true)
 |-- 252304: string (nullable = true)
 |-- 100305: string (nullable = true)
 |-- 0306: string (nullable = true)
 |-- 0307: string (nullable = true)
 |-- 0308: string (nullable = true)
 |-- 0309: string (nullable = true)
 |-- 0310: string (nullable = true)
 |-- 0311: string (nullable = true)
 |-- 0312: string (nullable = true)
 |-- 0313: string (nullable = true)
 |-- 0314: string (nullable = true)
 |-- 100315: string (nullable = true)
 |-- 252316: string (nullable = true)
 |-- 252317: string (nullable = true)
 |-- 88: string (nullable = true)
 |-- 0319: string (nullable = true)
 |-- 0320: string (nullable = true)
 |-- 0321: string (nullable = true)
 |-- 0322: string (nullable = true)
 |-- 0323: string (nullable = true)
 |-- 11324: string (nullable = true)
 |-- 171325: string (nullable = true)
 |-- 252326: string (nullable = true)
 |-- 252327: string (nullable = true)
 |-- 235: string (nullable = true)
 |-- 175: string (nullable = true)
 |-- 178: string (nullable = true)
 |-- 252331: string (nullable = true)
 |-- 252332: string (nullable = true)
 |-- 224: string (nullable = true)
 |-- 0334: string (nullable = true)
 |-- 0335: string (nullable = true)
 |-- 0336: string (nullable = true)
 |-- 0337: string (nullable = true)
 |-- 0338: string (nullable = true)
 |-- 0339: string (nullable = true)
 |-- 0340: string (nullable = true)
 |-- 0341: string (nullable = true)
 |-- 15342: string (nullable = true)
 |-- 209343: string (nullable = true)
 |-- 252344: string (nullable = true)
 |-- 233345: string (nullable = true)
 |-- 12346: string (nullable = true)
 |-- 0347: string (nullable = true)
 |-- 0348: string (nullable = true)
 |-- 0349: string (nullable = true)
 |-- 0350: string (nullable = true)
 |-- 49: string (nullable = true)
 |-- 177352: string (nullable = true)
 |-- 252353: string (nullable = true)
 |-- 252354: string (nullable = true)
 |-- 89355: string (nullable = true)
 |-- 26: string (nullable = true)
 |-- 0357: string (nullable = true)
 |-- 2358: string (nullable = true)
 |-- 166: string (nullable = true)
 |-- 252360: string (nullable = true)
 |-- 252361: string (nullable = true)
 |-- 0362: string (nullable = true)
 |-- 0363: string (nullable = true)
 |-- 0364: string (nullable = true)
 |-- 0365: string (nullable = true)
 |-- 0366: string (nullable = true)
 |-- 0367: string (nullable = true)
 |-- 0368: string (nullable = true)
 |-- 0369: string (nullable = true)
 |-- 96370: string (nullable = true)
 |-- 253371: string (nullable = true)
 |-- 253372: string (nullable = true)
 |-- 59: string (nullable = true)
 |-- 0374: string (nullable = true)
 |-- 0375: string (nullable = true)
 |-- 0376: string (nullable = true)
 |-- 0377: string (nullable = true)
 |-- 11378: string (nullable = true)
 |-- 177379: string (nullable = true)
 |-- 255: string (nullable = true)
 |-- 253381: string (nullable = true)
 |-- 92: string (nullable = true)
 |-- 0383: string (nullable = true)
 |-- 0384: string (nullable = true)
 |-- 0385: string (nullable = true)
 |-- 0386: string (nullable = true)
 |-- 155: string (nullable = true)
 |-- 253388: string (nullable = true)
 |-- 128: string (nullable = true)
 |-- 0390: string (nullable = true)
 |-- 0391: string (nullable = true)
 |-- 0392: string (nullable = true)
 |-- 0393: string (nullable = true)
 |-- 0394: string (nullable = true)
 |-- 0395: string (nullable = true)
 |-- 0396: string (nullable = true)
 |-- 0397: string (nullable = true)
 |-- 143398: string (nullable = true)
 |-- 252399: string (nullable = true)
 |-- 252400: string (nullable = true)
 |-- 10: string (nullable = true)
 |-- 0402: string (nullable = true)
 |-- 0403: string (nullable = true)
 |-- 0404: string (nullable = true)
 |-- 12405: string (nullable = true)
 |-- 171406: string (nullable = true)
 |-- 252407: string (nullable = true)
 |-- 216: string (nullable = true)
 |-- 110: string (nullable = true)
 |-- 13: string (nullable = true)
 |-- 0411: string (nullable = true)
 |-- 0412: string (nullable = true)
 |-- 0413: string (nullable = true)
 |-- 3414: string (nullable = true)
 |-- 180: string (nullable = true)
 |-- 232416: string (nullable = true)
 |-- 24417: string (nullable = true)
 |-- 0418: string (nullable = true)
 |-- 0419: string (nullable = true)
 |-- 0420: string (nullable = true)
 |-- 0421: string (nullable = true)
 |-- 0422: string (nullable = true)
 |-- 0423: string (nullable = true)
 |-- 0424: string (nullable = true)
 |-- 0425: string (nullable = true)
 |-- 143426: string (nullable = true)
 |-- 252427: string (nullable = true)
 |-- 170: string (nullable = true)
 |-- 2429: string (nullable = true)
 |-- 0430: string (nullable = true)
 |-- 0431: string (nullable = true)
 |-- 0432: string (nullable = true)
 |-- 135433: string (nullable = true)
 |-- 252434: string (nullable = true)
 |-- 209435: string (nullable = true)
 |-- 19: string (nullable = true)
 |-- 0437: string (nullable = true)
 |-- 0438: string (nullable = true)
 |-- 0439: string (nullable = true)
 |-- 0440: string (nullable = true)
 |-- 0441: string (nullable = true)
 |-- 12442: string (nullable = true)
 |-- 252443: string (nullable = true)
 |-- 132: string (nullable = true)
 |-- 0445: string (nullable = true)
 |-- 0446: string (nullable = true)
 |-- 0447: string (nullable = true)
 |-- 0448: string (nullable = true)
 |-- 0449: string (nullable = true)
 |-- 0450: string (nullable = true)
 |-- 0451: string (nullable = true)
 |-- 0452: string (nullable = true)
 |-- 0453: string (nullable = true)
 |-- 249454: string (nullable = true)
 |-- 252455: string (nullable = true)
 |-- 96456: string (nullable = true)
 |-- 0457: string (nullable = true)
 |-- 0458: string (nullable = true)
 |-- 0459: string (nullable = true)
 |-- 21: string (nullable = true)
 |-- 248461: string (nullable = true)
 |-- 246: string (nullable = true)
 |-- 34463: string (nullable = true)
 |-- 0464: string (nullable = true)
 |-- 0465: string (nullable = true)
 |-- 0466: string (nullable = true)
 |-- 0467: string (nullable = true)
 |-- 5468: string (nullable = true)
 |-- 61: string (nullable = true)
 |-- 234: string (nullable = true)
 |-- 152: string (nullable = true)
 |-- 3472: string (nullable = true)
 |-- 0473: string (nullable = true)
 |-- 0474: string (nullable = true)
 |-- 0475: string (nullable = true)
 |-- 0476: string (nullable = true)
 |-- 0477: string (nullable = true)
 |-- 0478: string (nullable = true)
 |-- 0479: string (nullable = true)
 |-- 0480: string (nullable = true)
 |-- 0481: string (nullable = true)
 |-- 253482: string (nullable = true)
 |-- 252483: string (nullable = true)
 |-- 44: string (nullable = true)
 |-- 0485: string (nullable = true)
 |-- 0486: string (nullable = true)
 |-- 0487: string (nullable = true)
 |-- 145: string (nullable = true)
 |-- 252489: string (nullable = true)
 |-- 104: string (nullable = true)
 |-- 0491: string (nullable = true)
 |-- 0492: string (nullable = true)
 |-- 0493: string (nullable = true)
 |-- 46494: string (nullable = true)
 |-- 114: string (nullable = true)
 |-- 184: string (nullable = true)
 |-- 252497: string (nullable = true)
 |-- 149: string (nullable = true)
 |-- 34499: string (nullable = true)
 |-- 0500: string (nullable = true)
 |-- 0501: string (nullable = true)
 |-- 0502: string (nullable = true)
 |-- 0503: string (nullable = true)
 |-- 0504: string (nullable = true)
 |-- 0505: string (nullable = true)
 |-- 0506: string (nullable = true)
 |-- 0507: string (nullable = true)
 |-- 0508: string (nullable = true)
 |-- 0509: string (nullable = true)
 |-- 253510: string (nullable = true)
 |-- 252511: string (nullable = true)
 |-- 82: string (nullable = true)
 |-- 0513: string (nullable = true)
 |-- 0514: string (nullable = true)
 |-- 31: string (nullable = true)
 |-- 239516: string (nullable = true)
 |-- 252517: string (nullable = true)
 |-- 66518: string (nullable = true)
 |-- 39: string (nullable = true)
 |-- 89520: string (nullable = true)
 |-- 165: string (nullable = true)
 |-- 243522: string (nullable = true)
 |-- 252523: string (nullable = true)
 |-- 233524: string (nullable = true)
 |-- 126525: string (nullable = true)
 |-- 5526: string (nullable = true)
 |-- 0527: string (nullable = true)
 |-- 0528: string (nullable = true)
 |-- 0529: string (nullable = true)
 |-- 0530: string (nullable = true)
 |-- 0531: string (nullable = true)
 |-- 0532: string (nullable = true)
 |-- 0533: string (nullable = true)
 |-- 0534: string (nullable = true)
 |-- 0535: string (nullable = true)
 |-- 0536: string (nullable = true)
 |-- 0537: string (nullable = true)
 |-- 249538: string (nullable = true)
 |-- 252539: string (nullable = true)
 |-- 244: string (nullable = true)
 |-- 126541: string (nullable = true)
 |-- 98: string (nullable = true)
 |-- 143543: string (nullable = true)
 |-- 252544: string (nullable = true)
 |-- 252545: string (nullable = true)
 |-- 237: string (nullable = true)
 |-- 240: string (nullable = true)
 |-- 253548: string (nullable = true)
 |-- 252549: string (nullable = true)
 |-- 243550: string (nullable = true)
 |-- 174: string (nullable = true)
 |-- 17552: string (nullable = true)
 |-- 0553: string (nullable = true)
 |-- 0554: string (nullable = true)

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/sample.txt')
eg.show()

+----------+
|     value|
+----------+
| 1 2 3 4 5|
|   6 7 7 8|
|10 11 11 4|
+----------+

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/sample.txt')
eg1=eg.rdd.map(lambda x:x.value.split(' '))
eg1.collect()

[['1', '2', '3', '4', '5'], ['6', '7', '7', '8'], ['10', '11', '11', '4']]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/sample.txt')
eg1=eg.rdd.map(lambda x:x.value.split(' ')+['shalini'])
eg1.collect()

[['1', '2', '3', '4', '5', 'shalini'],
 ['6', '7', '7', '8', 'shalini'],
 ['10', '11', '11', '4', 'shalini']]

In [ ]:
# from pyspark.sql import SparkSession
# spark=SparkSession\
#       .builder\
#       .appName('some eg')\
#       .config('spark.some.config.option','some-value')\
#       .getOrCreate()
list1= spark.sparkContext.parallelize([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
def foo(x):
  return ' '.join(map(str,x))
ans=list1.map(foo)
res=ans.collect()
print(res)

NameError: name 'spark' is not defined

In [ ]:
def get_sum(x):
  return sum(x)
res=list1.map(get_sum)
ans=res.collect()
print(ans)

[10, 26, 42]

In [ ]:
def do_something(x):
  list2=[]
  for i in x:
    list2.append(int(i)*2)
  return list2
res=list1.map(do_something)
ans=res.collect()
print(ans)

[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24]]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/quiz1.txt')
def get_len(x):
  return len(x)
eg1=eg.rdd.map(lambda x:x.value.split(' '))
x=eg1.collect()
y=eg1.map(lambda words:list(map(get_len,words)))
z=y.collect()
ans=print(z)

[[2, 3, 3, 4], [4, 3, 3, 5, 0], [5]]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
list1= spark.sparkContext.parallelize([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
ans= list1.flatMap(lambda x :x)
res=ans.collect()
print(res)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
list1= spark.sparkContext.parallelize([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
ans= list1.filter(lambda x : 1==1)
res=ans.collect()
print(res)

[(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)]

In [ ]:
list1= spark.sparkContext.parallelize([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
ans= list1.filter(lambda x : x!='5,6,7,8')
res=ans.collect()
print(res)

[(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)]

In [ ]:
list1= spark.sparkContext.parallelize([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
def foo(x):
  if (9,10,11,12)==x:
    return False
  else:
    return True
ans= list1.filter(foo)
res=ans.collect()
print(res)

[(1, 2, 3, 4), (5, 6, 7, 8)]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/filter quiz.txt')
eg1=eg.rdd.flatMap(lambda x :x.value.split(' '))
res=eg1.collect()
print(res)

['this', 'mango', 'company', 'animal', 'cat', 'dog', 'ant', 'mic', 'laptop', 'chair', 'switch', 'mobile', 'am', 'charger', 'cover', 'amanda', 'any', 'alarm', 'ant']

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/filter quiz.txt')
eg1=eg.rdd.flatMap(lambda x :x.value.split(' '))
def withoutac(x):
  if x.startswith('a') or x.startswith('c'):
    return False
  else:
    return True
eg2=eg1.filter(withoutac)
eg3=eg2.collect()
print(eg3)

['this', 'mango', 'dog', 'mic', 'laptop', 'switch', 'mobile']

In [ ]:
res=eg1.filter(lambda x: not(x.startswith('a') or x.startswith('c')))
eg2=res.collect()
print(eg2)

['this', 'mango', 'dog', 'mic', 'laptop', 'switch', 'mobile']

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/sample.txt')
eg1=eg.rdd.flatMap(lambda x :x)
eg2=eg1.distinct().collect()
print(eg2)

['1 2 3 4 5', '6 7 7 8', '10 11 11 4']

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/quiz1.txt')
eg2=eg.rdd.flatMap(lambda x:(x.value.split(' ')))
eg3=eg2.map(lambda x:(x,len(x)))
eg4=eg3.groupByKey().mapValues(list).collect()
print(eg4)

[('Hi', [2]), ('how', [3]), ('are', [3, 3]), ('you?', [4]), ('hope', [4]), ('you', [3]), ('doing', [5]), ('', [0]), ('great', [5])]

In [ ]:

from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.read.format('text').load('/content/quiz1.txt')
eg2=eg.rdd.flatMap(lambda x:(x.value.split(' ')))
eg3=eg2.map(lambda x:(x,len(x)))
eg4=eg3.groupByKey().mapValues(list).collect()
print(eg4)

[('Hi', [2]), ('how', [3]), ('are', [3, 3]), ('you?', [4]), ('hope', [4]), ('you', [3]), ('doing', [5]), ('', [0]), ('great', [5])]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([('hi'),('how', 'are' ,'you'),('hi','you')])
eg2=eg.flatMap(lambda x:x)
eg3=eg2.map(lambda x:(x,len(x)))
#eg4=eg3.groupByKey().mapValues(list).collect()
#eg4=eg3.groupByKey().mapValues(tuple).collect()
print(eg4)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 30.0 failed 1 times, most recent failure: Lost task 1.0 in stage 30.0 (TID 35) (81083f943568 executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 1247, in main
    process()
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 1239, in process
    serializer.dump_stream(out_iter, outfile)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 274, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/util.py", line 83, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/rdd.py", line 4260, in map_values_fn
    return kv[0], f(kv[1])
TypeError: cannot convert dictionary update sequence element #0 to a sequence

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:784)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:766)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1049)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1048)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:195)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 1247, in main
    process()
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 1239, in process
    serializer.dump_stream(out_iter, outfile)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/serializers.py", line 274, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/local/lib/python3.10/dist-packages/pyspark/python/lib/pyspark.zip/pyspark/util.py", line 83, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/rdd.py", line 4260, in map_values_fn
    return kv[0], f(kv[1])
TypeError: cannot convert dictionary update sequence element #0 to a sequence

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:784)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:766)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1049)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([('hi'),('how', 'are' ,'you'),('hi','you')])
eg2=eg.flatMap(lambda x:x)
eg3=eg2.map(lambda x:(x,len(x)))
eg4=eg3.reduceByKey(lambda x,y:x+y).collect()
print(eg4)

[('h', 1), ('i', 1), ('are', 3), ('how', 3), ('you', 6), ('hi', 2)]

In [ ]:
#to get count of words
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([('hi'),('how', 'are' ,'you'),('hi','you')])
eg2=eg.flatMap(lambda x:x)
eg3=eg2.map(lambda x:(x,1))
eg4=eg3.reduceByKey(lambda x,y:x+y).collect()
print(eg4)

[('h', 1), ('i', 1), ('are', 1), ('how', 1), ('you', 2), ('hi', 1)]

In [ ]:
#Similar like above but using countByValue()function
#count by value
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([('hi'),('how', 'are' ,'you'),('hi','you')])
eg2=eg.flatMap(lambda x:x)
eg3=eg2.countByValue()
print(eg3)

defaultdict(<class 'int'>, {'h': 1, 'i': 1, 'how': 1, 'are': 1, 'you': 2, 'hi': 1})

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([('hi'),('how', 'are' ,'you'),('hi','you')])
eg2=eg.flatMap(lambda x:x).collect()

In [ ]:
eg2.saveAsTextFile('/content/filter_eg.txt')

AttributeError: 'list' object has no attribute 'saveAsTextFile'

In [ ]:
#using reduceByKey to get sum of the ratings and sum of the people who rated that specific movie'
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize({
("Inception, 9"),
("The Dark Knight, 8"),
("Inception, 7"),
("The Matrix, 10"),
("The Godfather, 9"),
("The Matrix, 8"),
("Pulp Fiction, 9"),
("The Godfather, 10"),
("Fight Club, 8"),
("Fight Club, 9")})
#eg1=eg.map(lambda x: (x.split(',')[0].strip(),int(x.split(',')[1].strip()))).collect()
eg1=eg.map(lambda x: (x.split(',')[0].strip(),(int(x.split(',')[1].strip()),1)))
eg2=eg1.reduceByKey(lambda x,y:(x[0]+y[0],x[1]+y[1])).collect()
print(eg2)

[('The Godfather', (19, 2)), ('Fight Club', (17, 2)), ('The Matrix', (18, 2)), ('Inception', (16, 2)), ('Pulp Fiction', (9, 1)), ('The Dark Knight', (8, 1))]

In [ ]:
#to get avg rating
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize({
("Inception, 9"),
("The Dark Knight, 8"),
("Inception, 7"),
("The Matrix, 10"),
("The Godfather, 9"),
("The Matrix, 8"),
("Pulp Fiction, 9"),
("The Godfather, 10"),
("Fight Club, 8"),
("Fight Club, 9")})
eg1=eg.map(lambda x: (x.split(',')[0].strip(),(int(x.split(',')[1].strip()),1)))
eg2=eg1.reduceByKey(lambda x,y:(x[0]+y[0],x[1]+y[1]))
eg3=eg2.map(lambda x:(x[0],x[1][0]/x[1][1])).collect()
print(eg3)

[('The Godfather', 9.5), ('Fight Club', 8.5), ('The Matrix', 9.0), ('Inception', 8.0), ('Pulp Fiction', 9.0), ('The Dark Knight', 8.0)]

In [ ]:
#to get avg rating
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize(['JAN, NY, 3',
'JAN, PA, 1',
'JAN, NJ, 2',
'JAN, CT, 4',
'FEB, PA, 1',
'FEB, NJ, 1',
'FEB, NY, 2',
'FEB, VT, 1',
'MAR, NJ, 2',
'MAR, NY, 1',
'MAR, VT, 2',
'MAR, PA, 3'])
eg1 = eg.map(lambda x: (x.split(',')[0].strip(), (int(x.split(',')[2].strip()), 1)))

# Aggregate the ratings and count the occurrences for each month
eg2 = eg1.reduceByKey(lambda x, y: (x[0] + y[0], x[1] + y[1]))

# Compute the average rating for each month
eg3 = eg2.map(lambda x: (x[0], x[1][0] / x[1][1])).collect()

# Print the results
print(eg3)

[('JAN', 2.5), ('FEB', 1.25), ('MAR', 2.0)]

In [ ]:
#to get min rating of eCH MOVIE
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize(['JAN, NY, 3',
'JAN, PA, 1',
'JAN, NJ, 2',
'JAN, CT, 4',
'FEB, PA, 1',
'FEB, NJ, 1',
'FEB, NY, 2',
'FEB, VT, 1',
'MAR, NJ, 2',
'MAR, NY, 1',
'MAR, VT, 2',
'MAR, PA, 3'])
eg1=eg.map(lambda x:(x.split(',')[1].strip(),int(x.split(',')[2].strip())))
eg2=eg1.reduceByKey(lambda x,y:(x if x<y else y)).collect()
print(eg2)

[('NY', 1), ('CT', 4), ('PA', 1), ('NJ', 1), ('VT', 1)]

In [ ]:
#to get max rating of eCH MOVIE
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize(['JAN, NY, 3',
'JAN, PA, 1',
'JAN, NJ, 2',
'JAN, CT, 4',
'FEB, PA, 1',
'FEB, NJ, 1',
'FEB, NY, 2',
'FEB, VT, 1',
'MAR, NJ, 2',
'MAR, NY, 1',
'MAR, VT, 2',
'MAR, PA, 3'])
eg1=eg.map(lambda x:(x.split(',')[1].strip(),int(x.split(',')[2].strip())))
eg2=eg1.reduceByKey(lambda x,y:(x if x>y else y)).collect()
print(eg2)

[('NY', 3), ('CT', 4), ('PA', 3), ('NJ', 2), ('VT', 2)]

In [ ]:
#show the total number of students enrolled.
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([
'age,gender,name,course,roll,marks,email',
'21,M,John Doe,Math,101,85,johndoe@example.com',
'22,F,Jane Smith,Science,102,90,janesmith@example.com',
'23,M,Michael Johnson,Engineering,103,75,michaelj@example.com',
'4,F,Emily Davis,Arts,104,95,emilyd@example.com',
'25,M,Chris Brown,Math,105,80,chrisb@example.com',
'26,F,Ashley Wilson,Science,106,88,ashleyw@example.com',
'27,M,David Moore,Engineering,107,78,davidm@example.com',
'28,F,Jessica Taylor,Arts,108,92,jessicat@example.com',
'29,M,Daniel Anderson,Math,109,84,daniela@example.com',
'30,F,Sarah Thomas,Science,110,89,saraht@example.com',
'31,M,James Jackson,Engineering,111,77,jamesj@example.com',
'32,F,Laura White,Arts,112,91,lauraw@example.com',
'33,M,Robert Harris,Math,113,86,roberth@example.com',
'34,F,Patricia Martin,Science,114,87,patriciam@example.com',
'35,M,Charles Thompson,Engineering,115,79,charlest@example.com',
'36,F,Linda Garcia,Arts,116,93,lindag@example.com',
'37,M,Joseph Martinez,Math,117,83,josephm@example.com',
'38,F,Barbara Robinson,Science,118,85,barbarar@example.com',
'39,M,Thomas Clark,Engineering,119,76,thomasc@example.com',
'40,F,Mary Rodriguez,Arts,120,94,maryr@example.com'])
header=eg.first()
eg1=eg.filter(lambda x:x!=header)
eg2=eg1.map(lambda x:(int(x.split(',')[0].strip()),x.split(',')[1].strip(),x.split(',')[2].strip(),x.split(',')[3].strip(),x.split(',')[4].strip(),x.split(',')[5].strip(),x.split(',')[6].strip())).collect()
eg2.count()

# eg1=eg.filter(lambda x:x!=)
# eg1=eg.map(lambda x :x.split(',')[2]).collect()
#print(eg2)

TypeError: list.count() takes exactly one argument (0 given)

In [ ]:
#show the total marks that students have achieved.
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([
'age,gender,name,course,roll,marks,email',
'21,M,John Doe,Math,101,85,johndoe@example.com',
'22,F,Jane Smith,Science,102,90,janesmith@example.com',
'23,M,Michael Johnson,Engineering,103,75,michaelj@example.com',
'4,F,Emily Davis,Arts,104,95,emilyd@example.com',
'25,M,Chris Brown,Math,105,80,chrisb@example.com',
'26,F,Ashley Wilson,Science,106,88,ashleyw@example.com',
'27,M,David Moore,Engineering,107,78,davidm@example.com',
'28,F,Jessica Taylor,Arts,108,92,jessicat@example.com',
'29,M,Daniel Anderson,Math,109,84,daniela@example.com',
'30,F,Sarah Thomas,Science,110,89,saraht@example.com',
'31,M,James Jackson,Engineering,111,77,jamesj@example.com',
'32,F,Laura White,Arts,112,91,lauraw@example.com',
'33,M,Robert Harris,Math,113,86,roberth@example.com',
'34,F,Patricia Martin,Science,114,87,patriciam@example.com',
'35,M,Charles Thompson,Engineering,115,79,charlest@example.com',
'36,F,Linda Garcia,Arts,116,93,lindag@example.com',
'37,M,Joseph Martinez,Math,117,83,josephm@example.com',
'38,F,Barbara Robinson,Science,118,85,barbarar@example.com',
'39,M,Thomas Clark,Engineering,119,76,thomasc@example.com',
'40,F,Mary Rodriguez,Arts,120,94,maryr@example.com'])
header=eg.first()
eg1=eg.filter(lambda x:x!=header)
#eg2=eg1.map(lambda x:(int(x.split(',')[0].strip()),x.split(',')[1].strip(),x.split(',')[2].strip(),x.split(',')[3].strip(),x.split(',')[4].strip(),x.split(',')[5].strip(),x.split(',')[6].strip())).collect()


eg2=eg1.map(lambda x :(x.split(',')[1],int(x.split(',')[5].strip())))
eg3=eg2.reduceByKey(lambda x,y:x+y).collect()
print(eg3)

[('M', 803), ('F', 904)]

In [ ]:
#show the average marks that students have achieved per course.
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
eg=spark.sparkContext.parallelize([
'age,gender,name,course,roll,marks,email',
'21,M,John Doe,Math,101,85,johndoe@example.com',
'22,F,Jane Smith,Science,102,90,janesmith@example.com',
'23,M,Michael Johnson,Engineering,103,75,michaelj@example.com',
'4,F,Emily Davis,Arts,104,95,emilyd@example.com',
'25,M,Chris Brown,Math,105,80,chrisb@example.com',
'26,F,Ashley Wilson,Science,106,88,ashleyw@example.com',
'27,M,David Moore,Engineering,107,78,davidm@example.com',
'28,F,Jessica Taylor,Arts,108,92,jessicat@example.com',
'29,M,Daniel Anderson,Math,109,84,daniela@example.com',
'30,F,Sarah Thomas,Science,110,89,saraht@example.com',
'31,M,James Jackson,Engineering,111,77,jamesj@example.com',
'32,F,Laura White,Arts,112,91,lauraw@example.com',
'33,M,Robert Harris,Math,113,86,roberth@example.com',
'34,F,Patricia Martin,Science,114,87,patriciam@example.com',
'35,M,Charles Thompson,Engineering,115,79,charlest@example.com',
'36,F,Linda Garcia,Arts,116,93,lindag@example.com',
'37,M,Joseph Martinez,Math,117,83,josephm@example.com',
'38,F,Barbara Robinson,Science,118,85,barbarar@example.com',
'39,M,Thomas Clark,Engineering,119,76,thomasc@example.com',
'40,F,Mary Rodriguez,Arts,120,94,maryr@example.com'])
header=eg.first()
eg1 = eg.filter(lambda x: x != header)

# Map to (course, (marks, 1)) tuples
eg2 = eg1.map(lambda x: (x.split(',')[3], (int(x.split(',')[5].strip()), 1)))

# Reduce by key to sum the marks and count the number of entries per course
eg3 = eg2.reduceByKey(lambda x, y: (x[0] + y[0], x[1] + y[1]))

# Map to (course, average_marks)
eg4 = eg3.map(lambda x: (x[0], x[1][0] / x[1][1])).collect()

# Print the result
print(eg4)

[('Science', 87.8), ('Arts', 93.0), ('Math', 83.6), ('Engineering', 77.0)]

In [ ]:
#no of students thta ghave passed and failed
eg2=eg1.map(lambda x:(x.split(',')[3].strip(),((1,0) if int(x.split(',')[5].strip())>50 else (0,1))))
eg3=eg2.reduceByKey(lambda x,y:(x[0]+y[0],x[1]+y[1])).collect()
#eg4 =eg3.map(lambda x: (x[0], x[1])).collect()
print(eg3)

[('Science', (5, 0)), ('Arts', (5, 0)), ('Math', (5, 0)), ('Engineering', (5, 0))]

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').load('/content/sm.csv')
df.show()

+---+------+----------------+-----------+----+-----+--------------------+
|age|gender|            name|     course|roll|marks|               email|
+---+------+----------------+-----------+----+-----+--------------------+
| 21|     M|        John Doe|       Math| 101|   85| johndoe@example.com|
| 22|     F|      Jane Smith|    Science| 102|   90|janesmith@example...|
| 23|     M| Michael Johnson|Engineering| 103|   75|michaelj@example.com|
|  4|     F|     Emily Davis|       Arts| 104|   95|  emilyd@example.com|
| 25|     M|     Chris Brown|       Math| 105|   80|  chrisb@example.com|
| 26|     F|   Ashley Wilson|    Science| 106|   88| ashleyw@example.com|
| 27|     M|     David Moore|Engineering| 107|   78|  davidm@example.com|
| 28|     F|  Jessica Taylor|       Arts| 108|   92|jessicat@example.com|
| 29|     M| Daniel Anderson|       Math| 109|   84| daniela@example.com|
| 30|     F|    Sarah Thomas|    Science| 110|   89|  saraht@example.com|
| 31|     M|   James Jackson|Engineering| 111|   77|  jamesj@example.com|
| 32|     F|     Laura White|       Arts| 112|   91|  lauraw@example.com|
| 33|     M|   Robert Harris|       Math| 113|   86| roberth@example.com|
| 34|     F| Patricia Martin|    Science| 114|   87|patriciam@example...|
| 35|     M|Charles Thompson|Engineering| 115|   79|charlest@example.com|
| 36|     F|    Linda Garcia|       Arts| 116|   93|  lindag@example.com|
| 37|     M| Joseph Martinez|       Math| 117|   83| josephm@example.com|
| 38|     F|Barbara Robinson|    Science| 118|   85|barbarar@example.com|
| 39|     M|    Thomas Clark|Engineering| 119|   76| thomasc@example.com|
| 40|     F|  Mary Rodriguez|       Arts| 120|   94|   maryr@example.com|
+---+------+----------------+-----------+----+-----+--------------------+

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').option('header','True').load('/content/sm.csv')
df.show()

+---+------+----------------+-----------+----+-----+--------------------+
|age|gender|            name|     course|roll|marks|               email|
+---+------+----------------+-----------+----+-----+--------------------+
| 21|     M|        John Doe|       Math| 101|   85| johndoe@example.com|
| 22|     F|      Jane Smith|    Science| 102|   90|janesmith@example...|
| 23|     M| Michael Johnson|Engineering| 103|   75|michaelj@example.com|
|  4|     F|     Emily Davis|       Arts| 104|   95|  emilyd@example.com|
| 25|     M|     Chris Brown|       Math| 105|   80|  chrisb@example.com|
| 26|     F|   Ashley Wilson|    Science| 106|   88| ashleyw@example.com|
| 27|     M|     David Moore|Engineering| 107|   78|  davidm@example.com|
| 28|     F|  Jessica Taylor|       Arts| 108|   92|jessicat@example.com|
| 29|     M| Daniel Anderson|       Math| 109|   84| daniela@example.com|
| 30|     F|    Sarah Thomas|    Science| 110|   89|  saraht@example.com|
| 31|     M|   James Jackson|Engineering| 111|   77|  jamesj@example.com|
| 32|     F|     Laura White|       Arts| 112|   91|  lauraw@example.com|
| 33|     M|   Robert Harris|       Math| 113|   86| roberth@example.com|
| 34|     F| Patricia Martin|    Science| 114|   87|patriciam@example...|
| 35|     M|Charles Thompson|Engineering| 115|   79|charlest@example.com|
| 36|     F|    Linda Garcia|       Arts| 116|   93|  lindag@example.com|
| 37|     M| Joseph Martinez|       Math| 117|   83| josephm@example.com|
| 38|     F|Barbara Robinson|    Science| 118|   85|barbarar@example.com|
| 39|     M|    Thomas Clark|Engineering| 119|   76| thomasc@example.com|
| 40|     F|  Mary Rodriguez|       Arts| 120|   94|   maryr@example.com|
+---+------+----------------+-----------+----+-----+--------------------+

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').option('inferSchema','True').option('header','True').load('/content/sm.csv')
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').option('header','True').load('/content/sm.csv')
df.printSchema()

root
 |-- age: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: string (nullable = true)
 |-- email: string (nullable = true)

In [ ]:
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').option('header','True').option('inferSchema','True').option('delimiter',',').load('/content/sm.csv')
df.show()
df.printSchema()

AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/content/sm.csv.

In [ ]:
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
schema=StructType([
    StructField('age',IntegerType(),True),
    StructField('gender',StringType(),True),
    StructField('name',StringType(),True),
    StructField('course',StringType(),True),
    StructField('roll',StringType(),True),
    StructField('marks',IntegerType(),True),
    StructField('email',StringType(),True),
])
from pyspark.sql import SparkSession
spark=SparkSession\
      .builder\
      .appName('some eg')\
      .config('spark.some.config.option','some-value')\
      .getOrCreate()
df=spark.read.format('csv').option('header','True').schema(schema).load('/content/sm.csv')
df.show()
df.printSchema()

+---+------+----------------+-----------+----+-----+--------------------+
|age|gender|            name|     course|roll|marks|               email|
+---+------+----------------+-----------+----+-----+--------------------+
| 21|     M|        John Doe|       Math| 101|   85| johndoe@example.com|
| 22|     F|      Jane Smith|    Science| 102|   90|janesmith@example...|
| 23|     M| Michael Johnson|Engineering| 103|   75|michaelj@example.com|
|  4|     F|     Emily Davis|       Arts| 104|   95|  emilyd@example.com|
| 25|     M|     Chris Brown|       Math| 105|   80|  chrisb@example.com|
| 26|     F|   Ashley Wilson|    Science| 106|   88| ashleyw@example.com|
| 27|     M|     David Moore|Engineering| 107|   78|  davidm@example.com|
| 28|     F|  Jessica Taylor|       Arts| 108|   92|jessicat@example.com|
| 29|     M| Daniel Anderson|       Math| 109|   84| daniela@example.com|
| 30|     F|    Sarah Thomas|    Science| 110|   89|  saraht@example.com|
| 31|     M|   James Jackson|Engineering| 111|   77|  jamesj@example.com|
| 32|     F|     Laura White|       Arts| 112|   91|  lauraw@example.com|
| 33|     M|   Robert Harris|       Math| 113|   86| roberth@example.com|
| 34|     F| Patricia Martin|    Science| 114|   87|patriciam@example...|
| 35|     M|Charles Thompson|Engineering| 115|   79|charlest@example.com|
| 36|     F|    Linda Garcia|       Arts| 116|   93|  lindag@example.com|
| 37|     M| Joseph Martinez|       Math| 117|   83| josephm@example.com|
| 38|     F|Barbara Robinson|    Science| 118|   85|barbarar@example.com|
| 39|     M|    Thomas Clark|Engineering| 119|   76| thomasc@example.com|
| 40|     F|  Mary Rodriguez|       Arts| 120|   94|   maryr@example.com|
+---+------+----------------+-----------+----+-----+--------------------+

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)